---
- hosts: nodes
  become: yes
  gather_facts: yes

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: usuario
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    
    - name: Execute script
      ansible.builtin.script: ../scripts/actualizacion.sh
      register: script


